### ISSUE TITLE
Proposal in reserve suggested

### ISSUE THREAD

**Issue by manonthemat** [Project-Catalyst/pa-tool#48]
This proposal was suggested to me right now.

![pa](https://user-images.githubusercontent.com/5065940/177698781-42601dd4-045e-4664-a3f0-aedd3a5c6b5d.png)

https://cardano.ideascale.com/c/idea/416625

This proposal made it somehow into the assessment stage, but already got archived 23 hours ago.

Seems like the data needs to catch up?

**Comment by coire1** [comment]
Yeah, unfortunately proposals data are not updated automatically. Now everything should be in sync.
Thanks for reporting!
